# Generated by Django 5.2.8 on 2025-11-26 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='products_or_status_bd22a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='products_or_created_328796_idx'),
        ),
    ]
